#%RAML 1.0
title: Example include binary file

/binary:
    get:
        responses:
            200:
                body:
                    image/png:
                        type: file
                        fileTypes: ['*/*']
                        example: !include file.png
